apiVersion: 1

playlists:
  - name: Sirios Mosaic — Observatory Loop
    interval: 30s
    spec:
      items:
        - type: dashboard_by_uid
          title: "Home"
          uid: sirios-mosaic-home
        - type: dashboard_by_uid
          title: "Overview"
          uid: sirios-mosaic-overview
        - type: dashboard_by_uid
          title: "Performance & Errors"
          uid: sirios-mosaic-perf
        - type: dashboard_by_uid
          title: "Entities Deep Dive"
          uid: sirios-mosaic-entities
        - type: dashboard_by_uid
          title: "Operations View"
          uid: sirios-mosaic-ops
