apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PROM
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    uid: LOKI
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: PROM
          matcherRegex: "request_id=(\\w{8}-\\w{4}-\\w{4}-\\w{4}-\\w{12})"
          name: request_id
          url: ""
