apiVersion: 1
contactPoints:
  - orgId: 1
    name: default
    receivers:
      - uid: email-default
        type: email
        settings:
          addresses: you@example.com
          singleEmail: true
